/*
 * about.java
 *
 * Created on July 1, 2001, 8:29 AM
 */

/**
 *
 * @author  cnappi
 */
public class aboutRC extends javax.swing.JDialog {

    /** Creates new form about */
    public aboutRC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabelAboutText.setText("Remote Control Version 0.1");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabelAboutText = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jLabelAboutText.setText("   About Text");
        getContentPane().add(jLabelAboutText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 340, 160));
        
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        
        getContentPane().add(jButtonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));
        
        pack();
    }//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // Add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new aboutRC(new javax.swing.JFrame(), true).show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAboutText;
    private javax.swing.JButton jButtonOK;
    // End of variables declaration//GEN-END:variables

}
