/*
 * remoteControl.java
 *
 * Created on June 30, 2001, 10:07 PM
 */

/**
 *
 * @author  cnappi
 */
public class controlRemote extends javax.swing.JFrame {

    /** Creates new form remoteControl */
    public controlRemote() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jMenuBarMain1 = new javax.swing.JMenuBar();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemLoad = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();
        jTabbedPaneMain = new javax.swing.JTabbedPane();
        jPanelProtocol = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanelDeviceCodes = new javax.swing.JPanel();
        jPanelKeyMapping = new javax.swing.JPanel();
        jPanelUpgradeCode = new javax.swing.JPanel();
        
        jMenuBarMain1.setPreferredSize(new java.awt.Dimension(400, 400));
        jMenuBarMain1.setMinimumSize(new java.awt.Dimension(30, 30));
        jMenuBarMain1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jMenuFile.setText("File");
        jMenuItemLoad.setText("Load");
        jMenuFile.add(jMenuItemLoad);
        jMenuItemSave.setText("Save");
        jMenuFile.add(jMenuItemSave);
        jMenuBarMain.add(jMenuFile);
        jMenuHelp.setText("About");
        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        
        jMenuHelp.add(jMenuItemAbout);
        jMenuBarMain.add(jMenuHelp);
        
        setTitle("Control Remote");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        jTabbedPaneMain.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jPanelProtocol.setPreferredSize(new java.awt.Dimension(640, 400));
        jPanelProtocol.setMinimumSize(new java.awt.Dimension(640, 400));
        jPanelProtocol.add(jDesktopPane1);
        
        jTabbedPaneMain.addTab("Protocol", jPanelProtocol);
        
        jTabbedPaneMain.addTab("Device Codes", jPanelDeviceCodes);
        
        jTabbedPaneMain.addTab("Key Mapping", jPanelKeyMapping);
        
        jTabbedPaneMain.addTab("Upgrade Code", jPanelUpgradeCode);
        
        jTabbedPaneMain.setSelectedIndex(0);
        
        getContentPane().add(jTabbedPaneMain, java.awt.BorderLayout.CENTER);
        
        setJMenuBar(jMenuBarMain);
        pack();
    }//GEN-END:initComponents

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jMenuItemLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoadActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jMenuItemLoadActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // Add your handling code here:
        new aboutRC(this,true).show();
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new controlRemote().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarMain1;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemLoad;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JTabbedPane jTabbedPaneMain;
    private javax.swing.JPanel jPanelProtocol;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanelDeviceCodes;
    private javax.swing.JPanel jPanelKeyMapping;
    private javax.swing.JPanel jPanelUpgradeCode;
    // End of variables declaration//GEN-END:variables

}
